# Builds and deploys the pipeline depending on input
name: Build/Deploy

on:
  workflow_dispatch:
    inputs:
      deploy-build:
        type: boolean
        default: false
        description: Deploy page after building
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{inputs.deploy-build == true}}
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: (${{inputs.deploy-build == true}} || github.event.pull_request.merged) && github.ref == 'refs/heads/master'
    steps:
      - run: echo ${{inputs.deploy-build == true}}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
